In [3]:
from tabpfn import TabPFNRegressor

In [34]:
import torch

batch1 = torch.load('/Users/jfeit/tabular/mcpfn/prior/batch_000000.pt')

In [48]:
batch1['X']

torch.Size([26227712])

In [46]:
batch1['y'].shape

torch.Size([512, 1024])

In [43]:
batch1['d']

tensor([ 13,  13,  13,  13,  36,  36,  36,  36,  37,  37,  37,  37,  47,  47,
         47,  47,  42,  42,  42,  42,  97,  97,  97,  97,  37,  37,  37,  37,
         75,  75,  75,  75,  43,  43,  43,  43,  70,  70,  70,  70,  73,  74,
         74,  74,  55,  55,  55,  55,  46,  46,  46,  46,  94,  94,  94,  94,
         18,  18,  18,  18,  60,  60,  60,  60,  44,  44,  44,  44,  83,  83,
         83,  83,  47,  47,  47,  47,  36,  36,  36,  36,  20,  20,  20,  20,
         30,  30,  30,  30,  43,  43,  43,  43,  61,  61,  61,  61,  33,  33,
         33,  33,   5,   5,   5,   5, 100, 100, 100, 100,  39,  39,  39,  39,
          4,   4,   4,   4,  79,  79,  79,  79,  97,  97,  97,  97,  80,  80,
         80,  80,  62,  62,  62,  62,  10,  10,  10,  10,  52,  52,  52,  52,
         82,  82,  82,  82,   8,   8,   8,   8,  58,  58,  58,  58,  78,  78,
         78,  78,  12,  12,  12,  12,  72,  72,  72,  72,  80,  80,  80,  80,
         97,  99,  99,  99,  29,  29,  29,  29,  55,  55,  55,  

In [5]:
# Load diabetes dataset
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

# Split into train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
model = TabPFNRegressor(device="cpu")

model.fit(X_train, y_train)

/Users/jfeit/tabular/.venv/lib/python3.10/site-packages/tabpfn/regressor.py:460: UserWarning: Running on CPU with more than 200 samples may be slow.
Consider using a GPU or the tabpfn-client API: https://github.com/PriorLabs/tabpfn-client
  check_cpu_warning(


TabPFNRegressor(device='cpu')

In [8]:
model.predict(X_test)

array([151.11984 , 181.23395 , 152.39328 , 270.66843 , 116.048615,
        98.57599 , 280.28693 , 204.01453 ,  92.98259 , 104.42664 ,
        97.20478 , 156.68275 ,  79.03818 , 221.29614 ,  95.34686 ,
       113.29086 , 232.82916 , 263.02063 , 202.36508 , 226.96875 ,
       214.99869 ,  90.550705,  76.045364, 204.91766 , 148.44948 ,
       159.32785 , 191.49872 , 179.13577 ,  71.97873 , 108.86607 ,
       166.0928  ,  90.06023 , 127.83388 , 188.93164 , 168.59038 ,
       215.19928 , 119.307785, 116.949844, 145.44827 ,  73.5537  ,
        77.18077 ,  99.99011 , 167.50687 , 147.84912 , 172.1824  ,
        76.06234 ,  81.00776 , 105.166275,  74.43037 , 161.98457 ,
       140.27203 ,  80.37433 , 104.437836, 101.16085 , 178.6712  ,
       142.64389 ,  89.98228 , 221.62193 , 118.673615,  80.18475 ,
       192.11647 , 208.27834 , 117.20884 ,  95.30004 , 119.84745 ,
       217.77151 , 175.74219 , 167.14984 , 120.115524, 143.5263  ,
       187.05565 , 203.7262  , 228.974   , 142.24925 ,  84.665

In [12]:
model.model_

PerFeatureTransformer(
  (encoder): SequentialEncoder(
    (0): RemoveEmptyFeaturesEncoderStep()
    (1): NanHandlingEncoderStep()
    (2): VariableNumFeaturesEncoderStep()
    (3): InputNormalizationEncoderStep()
    (4): VariableNumFeaturesEncoderStep()
    (5): LinearInputEncoderStep(
      (layer): Linear(in_features=4, out_features=192, bias=False)
    )
  )
  (y_encoder): SequentialEncoder(
    (0): NanHandlingEncoderStep()
    (1): LinearInputEncoderStep(
      (layer): Linear(in_features=2, out_features=192, bias=True)
    )
  )
  (transformer_encoder): LayerStack(
    (layers): ModuleList(
      (0-11): 12 x PerFeatureEncoderLayer(
        (self_attn_between_features): MultiHeadAttention()
        (self_attn_between_items): MultiHeadAttention()
        (mlp): MLP(
          (linear1): Linear(in_features=192, out_features=768, bias=False)
          (linear2): Linear(in_features=768, out_features=192, bias=False)
        )
        (layer_norms): ModuleList(
          (0-2): 3 x 

In [29]:
import numpy as np

def create_train_test_sets(X):
    # Get missing indices in X
    missing_indices = np.where(np.isnan(X))
    
    non_missing_indices = np.where(~np.isnan(X))
    
    train_X = np.zeros((len(non_missing_indices[0]), X.shape[0] + X.shape[1] - 2))
    train_y = np.zeros(len(non_missing_indices[0]))
    test_X = np.zeros((len(missing_indices[0]), X.shape[0] + X.shape[1] - 2))
    test_y = np.zeros(len(missing_indices[0]))
    
    for k, (i,j) in enumerate(zip(non_missing_indices[0], non_missing_indices[1])):
        # Get row without j-th column
        row = np.delete(X[i,:], j)
        # Get column without i-th row
        col = np.delete(X[:,j], i)
        
        # Create train set
        train_X[k,:] = np.concatenate((row, col))
        train_y[k] = X[i,j]
        
    
    for k, (i,j) in enumerate(zip(missing_indices[0], missing_indices[1])):
        # Get row without j-th column
        row = np.delete(X[i,:], j)
        # Get column without i-th row
        col = np.delete(X[:,j], i)
        
        # Create train set
        test_X[k,:] = np.concatenate((row, col))
        test_y[k] = np.nan
        
    return train_X, train_y, test_X, test_y
    
X = np.array([[1, 3, 5], [7, np.nan, 6], [-1, 2, np.nan]])
train_X, train_y, test_X, test_y = create_train_test_sets(X)

print(train_X)
print(train_y)
print(test_X)
print(test_y)

[[ 3.  5.  7. -1.]
 [ 1.  5. nan  2.]
 [ 1.  3.  6. nan]
 [nan  6.  1. -1.]
 [ 7. nan  5. nan]
 [ 2. nan  1.  7.]
 [-1. nan  3. nan]]
[ 1.  3.  5.  7.  6. -1.  2.]
[[ 7.  6.  3.  2.]
 [-1.  2.  5.  6.]]
[nan nan]


In [19]:
import torch

In [20]:
X_tnsr = torch.from_numpy(X)

tensor([[ 1.,  3.,  5.],
        [ 7., nan,  6.],
        [-1.,  2., nan]], dtype=torch.float64)